* I REALLY JUST WANT TO BE A PART OF SOMETHING AI RELATED BECAUSE IT'S A PASSION OF MINE*

Python developer. Currently learning Rust. With ~1-year experience building and running Multi-Agent Simulations with different configs .See Commune_ResearchLab and/or  COMMUNE_PROJECT-V3, 
ResearchLab, 
Commune-ResearchLab  

*Driven to contribute to ANY open-source project.* 
 *I am currently trying to build on my networking*
*I just want to be apart of something AI related.* 




Seeking Open-Source Collaboration & Mentorship

I am an enthusiastic developer with a strong foundation in Python for data processing, scripting, and system automation, and I am currently committed to mastering Rust to build high-performance, robust systems—a journey I've started with my own time-series ChromoDB project. My goal is to move beyond personal projects and contribute meaningfully to a collaborative open-source environment. I am actively seeking a project that intersects with my skill set, particularly those focused on networking, infrastructure, or data pipeline optimization, where the combination of Python's flexibility and Rust's speed offers tangible benefits.

My drive to join an open-source team is rooted in the desire to build professional networks and absorb best engineering practices. I am looking for a project where I can learn from experienced developers, contribute scalable code, and participate actively in code reviews and architectural discussions. Whether contributing Python modules for tooling or diving into low-level Rust for performance bottlenecks, I offer dedication, clear communication, and an eagerness to tackle complex challenges. I am ready to commit time and focus to help an established project grow and deliver high-quality results to the community.

The best way to reach me is Whatapp: 856-504-7989 *NOTE: I will NEVER answer a random, not scheduled phone call. Or anything selling anything, I WILL NOT BUY IF IT LOOKS "SPAM

*The best way to reach me is via email: frankhymer2025@proton.me*

Cashapp is: $frankhymer85

As far as my phone goes, I will ONLY respond if it's via an encrypted messaging like Signal or Whatsapp, and via text. AGAIN NEVER pick up if its an unscheduled phone call. 
THANK YOU  
